install.packages("ggplot2")
install.packages("dplyr")
install.packages("magrittr")
install.packages("tidyr")
install.packages("stringr")
install.packages("readr")
install.packages("glue")
install.packages("purrr")
install.packages("tibble")
install.packages("forcats")
install.packages("lubridate")
install.packages("scales")
install.packages("readxl")

install.packages("rmarkdown")
